id: PCFC9EA3B
initial_creation_type: ocr
source_metadata:
  volumes:
    c82ed9e6ca4d49389de7e32f06fbcb48:
      base_file: v043.txt
      image_group_id: I1PD95888
      title: གཡུའི་ཐང་མ་ཀྲས་དགུ།
      total_pages: 1379
      volume_number: 43
