id: D0AE1085E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-23T08:33:43+00:00'
last_modified: '2022-05-30T06:56:44.549970+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    c246:
      image_group_id: I1PD95888
      title: གཡུའི་ཐང་མ་ཀྲས་དགུ།
      total_pages: 1379
      order: 43
      base_file: c246.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
